slack notification
vechain/thor pull request #667
Opened 2024-01-31 18:39 UTC by claytonneal

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

When unit tests fail on main branch send slack notification to team
Also adjusted the workflow to only run matrix job of unit tests on PR and push to main

## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Sample request to slack channel

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] New and existing E2E tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have not added any vulnerable dependencies to my code

2024-02-01 02:42 UTC, libotony requested changes

2024-02-01 02:42 UTC, libotony commented on .github/workflows/test.yaml
> +        if: always()  && github.ref == 'refs/heads/main' && (steps.unit-test.outcome == 'failure')
```suggestion
        if: always()  && github.ref == 'refs/heads/master' && (steps.unit-test.outcome == 'failure')
```

2024-02-03 00:06 UTC, claytonneal commented on .github/workflows/test.yaml
> +        if: always()  && github.ref == 'refs/heads/main' && (steps.unit-test.outcome == 'failure')
thanks! done in code review commit

2024-02-04 03:40 UTC, libotony approved these changes

2024-02-04 03:41 UTC, merged