feat: allow devs to publish images from branches
vechain/thor pull request #680
Opened 2024-03-19 16:25 UTC by darrenvechain

# Description

This change allows developers to publish a docker image from any branch to the github container registry

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

N/A

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] New and existing E2E tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have not added any vulnerable dependencies to my code

2024-03-21 15:01 UTC, otherview approved these changes
lgtm - couple of nits, nothing blocking imo

Worth making a few test runs in real env (perhaps not the releases tho unless it's temporarly turned into a noop)

2024-03-21 15:04 UTC, darrenvechain commented on .github/workflows/on-master-commit.yaml
> +      - 'master-*'
Ya I wasn't sure on this one, we previously had this on unit tests. Should we remove @libotony ?


<img width="289" alt="image" src="https://github.com/vechain/thor/assets/107671032/6badebf1-2ad9-4546-a97c-cf10632a7a14">

2024-03-21 15:08 UTC, libotony commented on .github/workflows/on-master-commit.yaml
> +      - 'master-*'
Let's remove it first, if we get a requirement for it running on other branches, then we figure it out.

2024-03-21 15:09 UTC, libotony commented on .github/workflows/on-master-commit.yaml
> +      - 'master-*'
Was introduced via #667

2024-03-21 15:10 UTC, darrenvechain commented on .github/workflows/on-master-commit.yaml
> +      - 'master-*'
Okay, its resolved!

2024-03-21 15:27 UTC, libotony commented
Do we do RC release on GitHub release? Usually, we would RC releases to production if it was tested ok. If we do RC release on GithHub, do we need to write release notes for both RC and production releases?

2024-03-21 15:41 UTC, darrenvechain commented
> Do we do RC release on GitHub release? Usually, we would RC releases to production if it was tested ok. If we do RC release on GithHub, do we need to write release notes for both RC and production releases?

@libotony you can chose the previous target when generating release notes, is this what you mean? See screenshot: <img width="1026" alt="image" src="https://github.com/vechain/thor/assets/107671032/bf67b46c-f261-414a-8f45-3484c89fe350">

BTW, the `-rc` is not mandatory, you can use any suffix you like and it will publish with that suffix, I guess the description just has the example

You can also see an example of releases here:
https://github.com/darrenvechain/docker-publish-testing/releases

2024-03-25 14:32 UTC, libotony requested changes

2024-03-25 16:31 UTC, darrenvechain commented
Hey @libotony I added the linter to the master file. Another option (if we want) could be to always run the linter and tests before docker publish, like in this commit. WDYT? https://github.com/vechain/thor/commit/0e645b93d7a0fd42dac6313d6e304c59b4659ddc

I guess the good part is that tests and linters always run before docker publish. Bad part is that actions become nested and slightly harder to follow, eg see this PR: https://github.com/darrenvechain/thor/pull/26 - unit tests fall under `Docker Publish` which doesn't make much sense:

<img width="1060" alt="image" src="https://github.com/vechain/thor/assets/107671032/fc9ee7ef-f04c-4ad3-8f06-9f6747efd44f">

2024-03-25 16:43 UTC, libotony commented
> Hey @libotony I added the linter to the master file. Another option (if we want) could be to always run the linter and tests before docker publish, like in this commit. WDYT? [0e645b9](https://github.com/vechain/thor/commit/0e645b93d7a0fd42dac6313d6e304c59b4659ddc)

I think it's not necessary to run unit tests before docker publishes. I propose running linter on master is I remember that the linter action has  a feature that only linting changed codes on PRs, so a full lint on master might be necessary.

2024-03-25 16:49 UTC, libotony approved these changes

2024-03-25 16:58 UTC, merged